const fs = require('fs');
const crypto = require('crypto');
const path = require('path');

console.log('🔒 Impulse Panel Session Secret Generator');
console.log('=========================================');

// Generate new secure session secret
const newSessionSecret = crypto.randomBytes(64).toString('hex');

console.log('✅ Generated new secure session secret!');
console.log('Secret length:', newSessionSecret.length, 'characters');
console.log('');

// Check if .env file exists
const envPath = path.join(process.cwd(), '.env');
const envExamplePath = path.join(process.cwd(), '.env.example');

if (fs.existsSync(envPath)) {
  // Update existing .env file
  let envContent = fs.readFileSync(envPath, 'utf8');
  
  if (envContent.includes('SESSION_SECRET=')) {
    // Replace existing SESSION_SECRET
    envContent = envContent.replace(/SESSION_SECRET=.*/g, `SESSION_SECRET=${newSessionSecret}`);
    fs.writeFileSync(envPath, envContent);
    console.log('✅ Updated SESSION_SECRET in .env file');
  } else {
    // Add SESSION_SECRET to .env file
    envContent += `\n# Session Security\nSESSION_SECRET=${newSessionSecret}\n`;
    fs.writeFileSync(envPath, envContent);
    console.log('✅ Added SESSION_SECRET to .env file');
  }
} else {
  // Create new .env file from template
  if (fs.existsSync(envExamplePath)) {
    let envContent = fs.readFileSync(envExamplePath, 'utf8');
    envContent = envContent.replace(/SESSION_SECRET=.*/g, `SESSION_SECRET=${newSessionSecret}`);
    fs.writeFileSync(envPath, envContent);
    console.log('✅ Created .env file with new SESSION_SECRET');
  } else {
    // Create minimal .env file
    const minimalEnv = `# Impulse Panel Environment Configuration
# Generated by session secret regenerator

SESSION_SECRET=${newSessionSecret}
DATABASE_URL=sqlite://impulse.db
PORT=3000
BASE_URI=http://localhost:3000
DOMAIN=localhost
NODE_ENV=production
`;
    fs.writeFileSync(envPath, minimalEnv);
    console.log('✅ Created new .env file with SESSION_SECRET');
  }
}

console.log('');
console.log('🔧 Next steps:');
console.log('1. Review your .env file');
console.log('2. Restart your application');
console.log('3. All users will need to log in again');
console.log('');
console.log('⚠️  IMPORTANT: Keep your .env file secure and never commit it to version control!');